### ISSUE TITLE
Missing repository.html sent to dead link.

### ISSUE THREAD

**Issue by d2iq-shadowbq** [kudobuilder/kudo.dev#228]
The KUDO repository needs better documentation:

**Linked here**

https://kudo.dev/docs/architecture.html#architecture-diagram

KUDO Repository provides significant convenience but is not strictly required. It provides an index of operators along with URLs they may be retrieved from. Read about the **operator repository** for more details on repositories and operator layout.

**Which page is affected?**:

https://kudo.dev/docs/repository.html

**What exactly is broken?**:

404 Error

**Which device do you use?**:

Any

**Anything else we need to know?**:

There are repo instructions that could be formalized from:

* https://kudo.dev/docs/runbooks/admin/local-repo.html#preconditions
* https://kudo.dev/docs/runbooks/admin/add-operator-to-repository.html
* https://kudo.dev/blog/announcing-kudo-0.6.0.html#release-highlights

And Additional missing content:

* https://github.com/kudobuilder/operators/blob/master/docs/Publishing.md

`https://kudo-repository.storage.googleapis.com/index.yaml`

Please also explain the `index.yaml` spec: 

```yaml
apiVersion: v1
entries:
  cassandra:
  - appVersion: 3.11.5
    digest: b9cb094860193be467923cb1cd2fdc1a12d9d47b15662b54a0d0689faabf0f65
    maintainers:
    - email: murilo@murilopereira.com
      name: Murilo Pereira
    name: cassandra
    urls:
    - https://kudo-repository.storage.googleapis.com/cassandra-0.1.1.tgz
    version: 0.1.1
  - appVersion: 3.11.4
    digest: da45a8e80c0f9a19eb88a487545dc0af7b51cd00ee3f7498154fac064893c140
    maintainers:
    - email: murilo@murilopereira.com
      name: Murilo Pereira
    name: cassandra
    urls:
    - https://kudo-repository.storage.googleapis.com/cassandra-0.1.0.tgz
    version: 0.1.0
generated: "2020-01-09T14:13:03.897073+01:00"
```
