### ISSUE TITLE
Updates for Community Content section

### ISSUE THREAD

**Issue by yankcrime** [kudobuilder/kudo.dev#24]
**What would you like to be added**:
There's been a bunch of KUDO-related content (videos etc.) created by the likes of @djannot and @kensipe.  It'd be great to get these collected and added to the website, maybe under the ['Community Content'](https://kudo.dev/community/#community-content) section.

**Comment by meichstedt** [comment]
Love the idea, and I remember we planned to have this a couple months ago.

It might be beneficial in the long run to render this based on metadata and provide various information, e.g. links to slides, a recording, maybe some URL. So we could collect the data something like this:

```yaml
content:
  type: event
  title: KUDO - Kubernetes Operators, the easy way
  author: Matt Jarvis
  date: 2019-05-14
  video: https://youtu.be/qAUmRfbd300
  slides: ...
content:
  type: blog-post
  title: Hitting the wall with YAML
  url: ...
```

I would then re-use the approach we have for events so that we can render events in the content section if they have e.g. link to a recording.
